name: 라이트하우스 CI - develop으로 푸시되었을 때 측정

on:
  push:
    branches: [develop]

jobs:
  lhci:
    name: Lighthouse 점수 자동 측정기
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './pokr-web'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: 패키지 설치
        run: |
          yarn

      - name: 웹 빌드
        run: |
          yarn build

      - name: Lighthouse CI 실행
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli
          lhci autorun || echo "Fail to Run Lighthouse CI!"

      - name: 점수 포매팅
        id: format_lighthouse_score
        uses: actions/github-script@v6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.setOutput('comments', "TEST")

      - name: PR에 코멘트 달기
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.format_lighthouse_score.outputs.comments}}
