name: pokr CD

on:
    push:
        branches: [develop]
env:
    PORT: 8080
    IMAGE: server
    CONTAINER: server
    OWNER_OR_ORGANIZATION: sundayTen
    REPOSITORY: pokr-server
    SERVER_USER: bitnami
    GIT_USER: fksk94
    BRANCH: develop

jobs:
    deploy:
        name: Deploy
        runs-on: [pokr]
        steps:
            - name: Check out source code
              uses: actions/checkout@v2
            - name: Pull source code
              run: |
                  cd /home/${{ env.SERVER_USER }}/${{ env.REPOSITORY }}
                  git pull https://${{ env.GIT_USER }}:${{ secrets.USER_TOKEN }}@github.com/${{ env.OWNER_OR_ORGANIZATION }}/${{ env.REPOSITORY }}.git ${{ env.BRANCH }}
            - name: Install Libraries
              run: pip3.11 install -r requirements.txt
            - name: Check
              run: pwd
            - name: Run Server
              run: |
                cp /home/${{ env.SERVER_USER }}/${{ env.REPOSITORY }}/.env ./.env
                nohup python3.11 main.py &