name: pokr CD

on:
    push:
        branches: [develop]
env:
    PORT: 8080
    IMAGE: server
    CONTAINER: server
    OWNER_OR_ORGANIZATION: sundayTen
    REPOSITORY: pokr-server
    SERVER_USER: bitnami
    GIT_USER: fksk94
    BRANCH: develop

jobs:
    deploy:
        name: Deploy
        runs-on: [pokr]
        steps:
            - name: Check out source code
              uses: actions/checkout@v2
            - name: Pull source code
              run: |
                  cd /home/${{ env.SERVER_USER }}/${{ env.REPOSITORY }}
                  git pull https://${{ env.GIT_USER }}:${{ secrets.USER_TOKEN }}@github.com/${{ env.OWNER_OR_ORGANIZATION }}/${{ env.REPOSITORY }}.git ${{ env.BRANCH }}
            - name: Docker build
              run: docker build -t ${{ env.IMAGE }} /home/${{ env.SERVER_USER }}/${{ env.REPOSITORY }}
            - name: Docker stop
              run: |
                  docker ps -f name=${{ env.CONTAINER }} -q | xargs --no-run-if-empty docker container stop
                  docker container ls -a -f name=${{ env.CONTAINER }} -q | xargs -r docker container rm
            - name: Docker run
              run: docker run -d --name ${{ env.CONTAINER }} -p ${{ env.PORT }}:${{ env.PORT }} -v /etc/localtime:/etc/localtime:ro -v /home/actions/assets/image:/image --restart always ${{ env.IMAGE }}
            - name: remove Docker <none> image
              run: if [ "$(docker images -f dangling=true -q)" != "" ]; then docker rmi $(docker images -f dangling=true -q); fi
